FROM node:latest AS react-build

WORKDIR /app/client

COPY client/package.json client/package-lock.json ./

RUN npm install

COPY client ./

RUN npm run build

FROM nginx:latest

COPY default.conf /etc/nginx/conf.d/default.conf

COPY --from=react-build /app/client/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
